
# General options
all:
  root: "/pollard/home/mgoldman/micro-glmm"
  output_fp: "/pollard/data/projects/mwas-projects/output/centroid_75_spa_nolog_noscale"
  genes_label_fp: "/pollard/data/projects/mwas-projects/gene_labels"
  verbose: "TRUE"
  pandb_dir: "/pollard/data/midas2-db/midas2db-uhgg-v1.5/pangenomes"
  centriod_cutoff: "centroid_90"
  data_dir_snp: "/pollard/data/projects/mwas-projects/merge_snps_20230925"
  data_dir_genes: "/pollard/data/projects/mwas-projects/merge_genes_cid.75"
  geneome_file: "/pollard/data/midas2-db/midas2db-uhgg-v1.5/genomes.tsv"
  metadata: "/pollard/home/mgoldman/micro-glmm/example_data/metadata_IBD_2023_10_18.tsv"
  SPECIES_IDs:  ["100217","102506","102545","102528"]
  centroid_prevalence_cutoff: .9
  num_samples: 30
snps:
  abs_depth_snps: 3
  median_depth_snps: 5
  n_tau: 0
  run_qp: FALSE
  formula: "y~age+1"
  n_CNV: 0

genes:
  SPA: "TRUE"
  q_value: .05
  alpha_value:  .05
  median_depth_genes: 3
  compare_to_glm: TRUE
  log_copynumber: TRUE
  scale_copynumber: TRUE
