
# General options
all:
  root: "/pollard/home/mgoldman/micro-glmm"
  output_fp: "/pollard/data/projects/mwas-projects/output"
  #specieslist_fp: "genomes.csv"
  pandb_dir: "/pollard/data/midas2-db/midas2db-uhgg-v1.5/pangenomes"
  centriod_cutoff: "centroid_75"
  data_dir_snp: "/pollard/data/projects/mwas-projects/merge_snps_20230925"
  data_dir_genes: "/pollard/data/projects/mwas-projects/merge_genes_cid.75"
  geneome_file: "/pollard/data/midas2-db/midas2db-uhgg-v1.5/genomes.tsv"
  metadata: "/pollard/home/mgoldman/micro-glmm/example_data/metadata_IBD_2023_10_18.tsv"
